### ISSUE TITLE
Erro when the app starts

### ISSUE THREAD

**Issue by FelipeTartarotti** [zGrav/xtream-iptv-player-v3#9]
Hi, how are you ?  I'm trying to install this app in my device and I get this error. 
Would you know what it could be ?

`
2019-05-30` 13:20:56.174 16723-16723/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-05-30 13:20:56.175 16723-16723/? E/libpersona: scanKnoxPersonas
2019-05-30 13:20:56.175 16723-16723/? E/libpersona: Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
2019-05-30 13:20:57.381 16723-16723/z.xtreamiptv.playerv3 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: z.xtreamiptv.playerv3, PID: 16723
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{z.xtreamiptv.playerv3/z.xtreamiptv.playerv3.view.activity.SplashActivity}: java.lang.ClassNotFoundException: Didn't find class "z.xtreamiptv.playerv3.view.activity.SplashActivity" on path: DexPathList[[zip file "/data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/base.apk", zip file "/data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/split_lib_directories_apk.apk", zip file "/data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/split_lib_resources_apk.apk"],nativeLibraryDirectories=[/data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/lib/arm, /data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/base.apk!/lib/armeabi-v7a, /data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/split_lib_directories_apk.apk!/lib/armeabi-v7a, /data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2850)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "z.xtreamiptv.playerv3.view.activity.SplashActivity" on path: DexPathList[[zip file "/data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/base.apk", zip file "/data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/split_lib_directories_apk.apk", zip file "/data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/split_lib_resources_apk.apk"],nativeLibraryDirectories=[/data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/lib/arm, /data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/base.apk!/lib/armeabi-v7a, /data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/split_lib_directories_apk.apk!/lib/armeabi-v7a, /data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1182)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2840)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7000) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
    	Suppressed: java.io.IOException: No original dex files found for dex location (arm) /data/app/z.xtreamiptv.playerv3-Xyv3toQZU_ebABGDnZN04Q==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:705)
2019-05-30 13:20:57.382 16723-16723/z.xtreamiptv.playerv3 E/AndroidRuntime:     at android.app.LoadedApk.getClassLoader(LoadedApk.java:739)
        at android.app.LoadedApk.getResources(LoadedApk.java:980)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2420)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5996)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1791)
        		... 6 more
`

**Comment by zGrav** [comment]
Didn't find class "z.xtreamiptv.playerv3.view.activity.SplashActivity"

Either something wrong with your build or you renamed something somewhere.

**Comment by BondasH** [comment]
Thanks fo your work!!!

Does not start ,after installing the application does not start
pop up info application error
Compiled with android-studio-ide
